import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      {/* for SEO */}
      <Head>
        <title>Financial AI chatbot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>This is the homepage for Financial AI chatbot</h2>
        <h2>Pratik</h2>
      </main>

      <footer></footer>
    </div>
  )
}
